"""V08 生成 Markdown 报告(数字全部读取 out/ 过程文件; 图片以相对路径 figures/ 引用)"""
import json, os, sys
import numpy as np, pandas as pd
sys.path.insert(0, 'code'); from q3lib import *
R = lambda s, f: pd.read_csv(os.path.join('out', s, f)); J = lambda s, f: json.load(open(os.path.join('out', s, f)))
out = []; W = out.append
def T(df, fmt='.4g', idx=False):
    d = df.copy()
    for c in d.columns:
        if pd.api.types.is_float_dtype(d[c]):
            d[c] = d[c].map(lambda x: '' if pd.isna(x) else format(x, fmt))
    W(d.to_markdown(index=idx)); W('')
def F(f, cap): W(f'![{cap}](figures/{f})'); W(f'*{cap}*'); W('')
e = lambda x: f'{x:.2e}'
G_ = G; law = Law(); Q0 = law.Q0
V1 = J('V01', 'V01_critical_context.json'); FQ = R('V01', 'V01_feasible_Lctx_set.csv')
MN = R('V02', 'V02_main_three_budgets_Lctx2048.csv'); FULL = R('V02', 'V02_optimal_allocation_full_grid.csv'); PC = R('V02', 'V02_mixture_gain_by_budget.csv')
TR = R('V03', 'V03_structural_transitions_detected.csv'); BP = R('V03', 'V03_segmented_powerlaw_breakpoints.csv'); SH = R('V03', 'V03_budget_shares_by_decade.csv')
AN = R('V04', 'V04_critical_budgets_analytic_vs_numeric.csv'); KK = R('V05', 'V05_KKT_check.csv'); MD = R('V05', 'V05_mixture_dominance_by_budget.csv')
UQ = R('V06', 'V06_uncertainty_quantiles.csv'); RS = R('V06', 'V06_regime_stability.csv'); Q0S = R('V06', 'V06_Q0_scenarios.csv'); CP = R('V06', 'V06_cost_parameter_sensitivity.csv')
m = MN.set_index('g_form'); mm = lambda C, gf, c: MN[(MN.C == C) & (MN.g_form == gf)][c].iloc[0]
a2 = AN[AN.L_ctx == 2048].set_index('g_form')
NMS = {k: GFORMS_EXT[k]['name'] for k in ['exp', 'power', 'log', 'filter']}

W('# 2026 年研究生数学建模竞赛 F 题 · 问题三求解报告')
W('## 算力约束下的多维资源联合优化与结构性转移'); W('')
W('> 输入：问题二的广义标度律与参数(`T06_generalized_law_params.json`)、问题一的推荐配比 p* 与各域质量 Q(A1 补全版)、附件 C7(`model_architecture_metadata.csv`)。全部数字由 `code/` 下的脚本计算，可逐项追溯到 `out/V01–V06` 的过程文件。数据核对：问题一、二的输出取自仓库 `AI output/Claude/` 目录，C7 取自 `real_attachments/`；经逐文件比对，与计算中使用的文件完全一致。C7 的 `training_data_TB` 字段数值与各模型公开的训练 token 数(以万亿计)吻合(如 Pythia 0.3 即 300B tokens、Llama-3 为 15T、Qwen2.5 为 18T)，本文按"万亿 token"解读。'); W('')
W('## 摘要'); W('')
W(f'1. **模型**。决策变量为 (N, D, Q)。目标函数采用问题二的广义标度律 L(N,D,Q,p)；约束为 6ND + D[g(Q)−g(Q₀)]₊ + ηNDL_ctx ≤ C。把注意力开销并入训练开销后，约束可写成 k(L)·ND + D·Δg(Q) ≤ C，其中 k(L) = 6(1+L/L_crit)。解析推出 **L_crit = 6/η = 30000**：C7 可行集 {{2048, 4096, 8192, 32768, 131072}} 中，前三档的注意力开销只有训练开销的 7%–27%，后两档则达到 1.09 倍和 4.37 倍。')
W(f'2. **配比 p 不必随预算联立求解**。广义律中配比项的系数 κ(R/R_1M)^η 对任意 (N,D,Q) 都为正，所以使 L 最小的 p 就是 argmin M6(p)，与预算无关(支配性论证，并已数值验证：5 个预算下 6 种候选配比的排序完全相同)。p 因此取问题一的推荐配比 p*。它在 C=10¹⁹、10²²、10²⁴ 时分别比 Pile 自然配比低 {PC[(PC.C==1e19)&(PC.g_form=="exp")].gain_pstar_vs_pref.iloc[0]:.4f}、{PC[(PC.C==1e22)&(PC.g_form=="exp")].gain_pstar_vs_pref.iloc[0]:.4f}、{PC[(PC.C==1e24)&(PC.g_form=="exp")].gain_pstar_vs_pref.iloc[0]:.4f}。')
W(f'3. **三档预算的最优解**(指数型成本，L_ctx=2048)。C=10¹⁹：N*={mm(1e19,"exp","N")/1e9:.3f}B，D*={mm(1e19,"exp","D")/1e9:.2f}B，Q*={mm(1e19,"exp","Q"):.3f}，**质量开销占 {mm(1e19,"exp","share_quality")*100:.1f}%**，D/N 仅为 {mm(1e19,"exp","tokens_per_param"):.1f}。C=10²²：Q*=1，质量份额降到 {mm(1e22,"exp","share_quality")*100:.1f}%，D/N={mm(1e22,"exp","tokens_per_param"):.0f}。C=10²⁴：质量份额 {mm(1e24,"exp","share_quality")*100:.1f}%，D/N={mm(1e24,"exp","tokens_per_param"):.0f}，N*={mm(1e24,"exp","N")/1e9:.1f}B。与"不投质量"的基线相比，Loss 分别降低 {mm(1e19,"exp","gain_vs_noQ"):.4f}、{mm(1e22,"exp","gain_vs_noQ"):.4f}、{mm(1e24,"exp","gain_vs_noQ"):.4f}。')
W(f'4. **存在明确的结构性转移**。本文定义了三类转移：Ⅰ 约束集切换，Ⅱ 标度指数突变，Ⅲ 边际优先序反转。沿预算增加依次出现："只扩规模(R0)"→"质量优先、压缩数据量换质量(R1/R2，质量份额峰值 31%–59%)"→"质量饱和，预算回流到规模，D/N 从 4 回升到 130+"→(若存在数据墙 1.8×10¹³ tokens)"D 触墙，N 的标度指数由约 0.5 跳到 1"。质量启动的临界预算 C₁ 在 10¹⁷–10¹⁹ 之间：指数型 {e(a2.loc["exp","C1_numeric"])}，幂函数型 {e(a2.loc["power","C1_numeric"])}，对数型 {e(a2.loc["log","C1_numeric"])}，改进型 {e(a2.loc["filter","C1_numeric"])}。所以题目给定的三档预算中，10¹⁹ 恰好落在转移区，而 10²² 与 10²⁴ 处于同一结构状态。')
W(f'5. **成本函数决定转移的"形态"**。指数型和本文提出的改进型(过滤产出率 γ_f/(1−Q))属于连续型转移：解析的一阶判据 g′(Q₀)=g′*(C) 与数值解相差 1%–3%。幂函数型和对数型属于跳跃型：Q* 从 Q₀ 直接跳到 1，由"等值切换条件" L*(Q₀) = L*(1) 给出，与数值解相差 <0.3%。改进型的 Q 永远达不到 1，所以在高预算下仍保留 6.5% 的质量开销，更符合"完美数据不可得"的现实。')
W(f'6. **L_ctx 的影响**：L_ctx 越长，训练(含注意力)越贵，而质量成本不受注意力影响，因此质量越早启动。从 2048 到 131072，C₁ 下降约 7 倍；在 131072 且 C=10²⁴ 时，注意力开销占预算的 {FULL[(FULL.C==1e24)&(FULL.g_form=="exp")&(FULL.L_ctx==131072)&(FULL.p=="p*")].share_attn.iloc[0]*100:.0f}%。参数不确定性(c_N、c_D 自助、η、Q_ref)不改变 10²² 与 10²⁴ 下的状态判定；在 10¹⁹ 处，指数型有 47% 的抽样落在 R2，说明这一档恰好位于转移边界附近。'); W('')

W('## 1  输入与数据'); W('')
T(pd.DataFrame([['广义标度律参数', '问题二 T06_generalized_law_params.json', f'E={G_["E"]:.4f}, A₁={G_["A1"]:.2f}, α={G_["alpha"]:.4f}, B₁={G_["B1"]:.2f}, β={G_["beta"]:.4f}, h_N={G_["hN"]:.4f}, h_D={G_["hD"]:.4f}, κ={G_["kappa"]:.4f}, η_p={G_["eta"]:.4f}'],
                ['基线质量 Q₀', '问题二 Q_ref(Pile 自然配比混合质量，A 口径)', f'{Q0:.4f}；情景分析另取问题一各域 Q'],
                ['配比 p', '问题一 S08_optimal_mixture.csv 集成 Top-100', f'ΔM6(p*) = {DM6["p*"]:.4f}(相对 p_ref)'],
                ['c_N、c_D 自助分布', '问题二 T04b_bootstrap_cN_cD.csv', '300 次单元簇自助，用于不确定性传播'],
                ['C7 上下文长度', 'real_attachments/C_efficiency_evolution/model_architecture_metadata.csv', f'45 个模型；可行集 {V1["feasible_L"]}；最大训练 token 18T(数据墙锚点)'],
                ['成本函数', '附录 B', '指数型 γ=10⁷, λ=6；幂函数型 γ=5×10⁹, λ=4；对数型 γ=2×10⁹, λ=10']], columns=['输入', '来源', '取值']))
W('## 2  模型建立'); W('')
W('### 2.1  优化模型'); W('')
W('$$\\min_{N,D,Q}\\; L(N,D,Q,p)=E+A_1[1+h_N(1-Q)]N^{-\\alpha}+B_1[1+h_D(1-Q)]D^{-\\beta}+\\kappa\\,\\Delta M6(p)\\Big(\\tfrac{R}{R_{1M}}\\Big)^{\\eta_p}$$'); W('')
W('$$\\text{s.t.}\\quad \\underbrace{6ND}_{C_{train}}+\\underbrace{D\\,[g(Q)-g(Q_0)]_+}_{C_Q}+\\underbrace{\\eta N D L_{ctx}}_{C_{attn}}\\le C,\\qquad Q_0\\le Q\\le 1,\\; N,D>0\\;(\\text{情景: } D\\le D_{max})$$'); W('')
W('令 **k(L) = 6 + ηL = 6(1 + L/L_crit)**，约束可改写为 k(L)·N·D + D·Δg(Q) ≤ C。由此得到两点：(1) 注意力开销等价于把每个"参数·token"的训练单价放大到 k(L)/6 倍，而质量成本只与 D 成比例、不含 N，所以 L 越大，质量相对越便宜；(2) 目标函数随 N、D、Q 单调下降，最优解处预算约束一定取等号，于是 N 可以用 D、Q 表示为 N = (C − D·Δg(Q))/(k·D)，问题降为关于 (ln D, Q) 的二维优化。')
W('### 2.2  临界上下文长度'); W('')
W('$$C_{attn}=C_{train}\\iff \\eta N D L=6ND\\iff L^{crit}_{ctx}=\\frac{6}{\\eta}=\\frac{6}{2\\times10^{-4}}=30000$$'); W('')
W(f'C7 中 45 个模型的上下文长度(表1)只有 5 个取值，其中 {V1["share_models_L_ge_Lcrit"]*100:.1f}% 的模型 ≥ L_crit，即这些模型的注意力开销超过训练开销。敏感性分析取 C7 的全部 5 个可行值，另加 L_crit 本身。'); W('')
T(FQ.rename(columns={'max_position_embeddings': 'L_ctx'}))
F('F09_C7_context.png', '图9  C7 中各模型的上下文长度与临界值 L_crit')
W('### 2.3  领域配比 p：由前两问确定，不参与联立'); W('')
W('**命题**：设 R(N,D,Q) = A₁[1+h_N(1−Q)]N^−α + B₁[1+h_D(1−Q)]D^−β > 0。对任意可行的 (N,D,Q)，L 关于 ΔM6(p) 严格递增(系数 κ(R/R_1M)^η > 0)。并且配比只改变数据的组成、不消耗算力(p 不出现在成本式中)。所以对任意预算 C，联合最优解中的 p 都等于 argmin_p M6(p)，与 C、L_ctx、成本函数无关。')
W('实际取值上，argmin M6 在单纯形边界附近需要外推，因此采用问题一给出的、有信赖域约束的集成推荐配比 p*。M6 信赖域最优解作为敏感性对照。数值验证(表2)：5 个预算量级下 6 种候选配比的 Loss 排序完全一致。'); W('')
T(MD.pivot(index='mixture', columns='C', values='L').reset_index().rename(columns=lambda c: f'C={c:.0e}' if isinstance(c, float) else c), '.4f')
W('### 2.4  质量成本函数：附录 B 三种形式与本文的改进型'); W('')
W('附录 B 的三种 g(Q) 在 Q=1 处都是有限值，即"完美数据"的代价有限。实际的数据筛选中，若只保留质量达到 Q 的那部分数据，保留比例 f 会随 Q→1 趋于 0，每得到一个合格 token 需要处理 1/f 个原始 token。取 f ∝ (1−Q)，得到本文提出的**改进型(过滤产出率模型)**：')
W(f'$$g_f(Q)=\\frac{{\\gamma_f}}{{1-Q}},\\qquad \\gamma_f=g_{{exp}}(0.9)\\times0.1={GAMMA_FILTER:.4g}$$'); W('')
W('标定方式是让它在 Q=0.9 处与指数型取值相同，以便比较。四种形式中，指数型、幂函数型和改进型的边际成本 g′ 递增(凸)，对数型的 g′ 递减(凹)。')
F('F01_cost_functions.png', '图1  质量成本函数及其边际成本')
W('### 2.5  求解方法、KKT 条件与解析临界值'); W('')
W('**求解**：在 (ln D, Q) 上做 260×161 的网格搜索，再用 L-BFGS-B 局部精修。另外用独立的 SLSQP 求解器在 (ln N, ln D, Q) 上带显式预算约束、多起点求解作为核验：' + f'{int(FULL.check_absdiff_L.notna().sum())}' + ' 个核验点的 |ΔL| 最大为 ' + f'{FULL.check_absdiff_L.max():.1e}' + '(`V02_optimal_allocation_full_grid.csv`)。')
W('**KKT 条件**：定义每 FLOP 的边际降 Loss 为 μ_N = −L_N/(kD)，μ_D = −L_D/(kN+Δg)，μ_Q = −L_Q/(D·g′(Q))。最优解满足 μ_N = μ_D = λ；当 Q 为内点时 μ_Q = λ，在上界时 μ_Q ≥ λ，在下界时 μ_Q ≤ λ。表3 在 12 个主解上逐一核验：内点解的 μ_Q/μ_N = 1.0000，上界解均 ≥1.28，μ_N 与 μ_D 的相对差为 0，预算约束恰好取等号。'); W('')
T(KK[['C', 'g_form', 'N', 'D', 'Q', 'rel_gap_N_D', 'lamQ_over_lamN', 'budget_slack', 'Q_status']])
W('**解析临界值**：在"不投质量"(Q=Q₀)的最优分配处，质量更划算的条件是 μ_Q > μ_N，即')
W("$$g'(Q_0) < g'^{*}(C)\\equiv k\\,\\frac{\\partial L/\\partial Q}{\\partial L/\\partial N}\\approx \\frac{k\\,[h_NA_1N^{-\\alpha}+h_DB_1D^{-\\beta}]}{\\alpha a_Q A_1N^{-\\alpha}}\\,N$$"); W('')
W('g′* 近似与最优参数量 N*(C) 成正比，随预算单调增长(图3)。因此一定存在一个临界预算 C₁：在它之上，质量的边际收益超过规模。对凸的 g(指数型、改进型)，Q* 在 C₁ 处连续地离开 Q₀，C₁ 由 g′(Q₀) = g′*(C₁) 确定。对边际成本增长缓慢的幂函数型和凹的对数型，最优 Q 在 C₁ 之前就会从 Q₀ 直接跳到 1，此时临界点由两个受限最优解的等值条件 L*(Q₀; C) = L*(1; C) 确定(跳跃型转移)。')
T(AN[['g_form', 'L_ctx', 'transition_type', 'C1_analytic_Q_leaves_Q0', 'C_jump_equal_value_Q0_vs_Qtop', 'C1_numeric', 'C2_analytic_Q_reaches_top', 'C2_numeric']], '.3e')
F('F03_gprime_star.png', "图3  质量启动判据：g′*(C) 随预算增长，越过 g′(Q₀) 后质量优先")

W('## 3  三档预算下的最优配置'); W('')
T(MN[['C', 'g_form', 'N', 'D', 'Q', 'tokens_per_param', 'L', 'share_train', 'share_quality', 'share_attn', 'regime', 'L_noQ', 'gain_vs_noQ']])
F('F04_three_budgets_shares.png', '图4  三档预算下的开销构成')
W('**解读**')
W(f'- **低预算 C=10¹⁹**：预算处在质量启动区。指数型和改进型取内点 Q*(分别为 {mm(1e19,"exp","Q"):.3f} 和 {mm(1e19,"filter","Q"):.3f})，幂函数型和对数型直接取 Q*=1。质量开销占 28%–56%。为了给质量腾出预算，D* 被大幅压缩(指数型 D/N={mm(1e19,"exp","tokens_per_param"):.1f}，远低于 Chinchilla 的约 20–30)，即"少而精"。这一档对成本函数的选择最敏感：对数型比指数型的 Loss 低 {mm(1e19,"exp","L")-mm(1e19,"log","L"):.3f}。')
W(f'- **中预算 C=10²²**：四种形式都达到或接近质量饱和(改进型 Q*={mm(1e22,"filter","Q"):.3f})，质量份额降到 2%–15%，D/N 回升到 50–82。')
W(f'- **高预算 C=10²⁴**：质量份额只有 0.3%–6.5%，配置接近"质量已饱和的 Chinchilla 分配"(D/N≈110–138)。成本函数带来的 Loss 差异 < {MN[MN.C==1e24].L.max()-MN[MN.C==1e24].L.min():.4f}，已可忽略。')
W('- **成本函数选择的影响**集中在低、中预算：它决定质量何时启动(C₁ 相差约 50 倍)、以连续还是跳跃方式启动、以及高预算下是否仍保留质量开销(只有改进型会保留)。'); W('')
W('## 4  结构性转移：定义、识别与结果'); W('')
W('### 4.1  数学定义'); W('')
W('记最优解为 x*(C) = (ln N*, ln D*, Q*)，约束活跃集为 𝒜(C) ⊆ {Q=Q₀, Q=1, D=D_max}，预算份额向量为 s(C) = (C_train, C_Q, C_attn)/C。若在区间 I 上同时满足 (i) 𝒜(C) 不变，(ii) 局部标度指数 e_X(C) = d ln X*/d ln C 连续，(iii) 在"不投质量"分配处，各资源的边际收益排序不变，则称最优配置在 I 上**结构稳定**(此时最优策略是同一族幂律，只随预算按比例放大)。在 C† 处出现以下任一情况即为**结构性转移**：')
W('- **类型 Ⅰ 约束集切换**：𝒜(C) 在 C† 处改变(R0 不投质量 → R1 质量内点 → R2 质量饱和 → +数据墙)；')
W('- **类型 Ⅱ 标度指数突变**：分段幂律 ln X* = a + b ln C + Σⱼ cⱼ(ln C − ln C†ⱼ)₊ 经 BIC 选出显著断点，且斜率变化 |cⱼ| > 0.1；')
W('- **类型 Ⅲ 边际优先序反转**：sign(μ_Q − μ_N) 在 C† 处改变，即"下一个 FLOP 该投给谁"发生反转。'); W('')
W('识别方法：在 10¹⁵–10²⁷ 上取 121 个对数等距预算点求解，用状态序列的变化定位类型 Ⅰ，再用二分法把转移点精确到 10⁻¹³ 相对精度(表4)；类型 Ⅱ 用 0–2 个断点的分段回归，按 BIC 选择断点数；类型 Ⅲ 逐点计算边际收益的排序。'); W('')
W('### 4.2  识别结果'); W('')
T(TR[(TR.L_ctx == 2048)])
T(BP[(BP.L_ctx == 2048)])
F('F02_budget_sweep.png', '图2  预算扫描：Q*、N*、D*、D/N、质量份额与最优 Loss')
F('F06_local_exponents.png', '图6  局部标度指数(类型 Ⅱ 转移)')
F('F07_regime_phase_diagram.png', '图7  (C, L_ctx) 状态相图(含数据墙情景)')
W('**解读(类比题面的"收入—支出结构")**')
W(f'1. **温饱阶段(C < C₁ ≈ 10¹⁷–10¹⁹)**：全部预算用于规模，Q*=Q₀，N*∝C^0.45、D*∝C^0.55，即经典 Chinchilla 分配。')
W('2. **"重视教育"阶段(C₁ 到约 10²⁰)**：质量的边际收益超过规模(类型 Ⅲ)，质量份额迅速升到 31%–59% 的峰值。由于质量成本按 token 计价，最优策略是**压缩数据量来换质量**，D*/N* 从约 25 降到 1.5–10(对数型最低、改进型最高)，D* 的局部指数出现负值(类型 Ⅱ)。')
W('3. **质量饱和阶段(C ≳ 10²⁰)**：Q* 到达上界(凸成本下为连续过渡，改进型渐近于 1)，每 token 的质量成本固定不变，而训练开销 kND 随规模超线性增长，所以质量份额按约 C^−0.45 衰减(C_Q/C ∝ D*/C ∝ C^{0.55−1})，预算重新回流到 N 和 D，D/N 单调回升到 130 以上。')
W(f'4. **数据墙阶段(存在上限 D_max=1.8×10¹³ 时，C ≈ 10²⁵)**：D 触墙，e_N 从约 0.5 跳到 1，e_D 降为 0，新增预算只能投给参数量(类型 Ⅰ+Ⅱ)。')
W('题目给定的 10¹⁹ 恰好位于第 2 阶段，10²² 与 10²⁴ 都处于第 3 阶段；若考虑数据墙，10²⁵ 以上进入第 4 阶段。'); W('')
T(SH.round(4), '.4f')
W('## 5  上下文长度 L_ctx 的敏感性(C7 可行集)'); W('')
fl = FULL[(FULL.p == 'p*') & (FULL.g_form == 'exp')][['C', 'L_ctx', 'N', 'D', 'Q', 'tokens_per_param', 'L', 'share_train', 'share_quality', 'share_attn', 'regime']]
T(fl)
F('F05_context_sensitivity.png', '图5  L_ctx 敏感性')
W(f'- L_ctx 按 k(L)/6 = 1 + L/L_crit 的倍数抬高训练单价：C7 的 5 个可行值分别对应 1.07、1.14、1.27、2.09、5.37 倍。在 L_crit 处注意力开销与训练开销相等；超过它之后，注意力成为最大的开销项(131072、C=10²⁴ 时占 {fl[(fl.C==1e24)&(fl.L_ctx==131072)].share_attn.iloc[0]*100:.0f}%)。')
W(f'- 同样的预算下，L_ctx 越长，N* 和 D* 越小(10²⁴ 时 N* 从 {fl[(fl.C==1e24)&(fl.L_ctx==2048)].N.iloc[0]/1e9:.1f}B 降到 {fl[(fl.C==1e24)&(fl.L_ctx==131072)].N.iloc[0]/1e9:.1f}B)，Loss 升高 {fl[(fl.C==1e24)&(fl.L_ctx==131072)].L.iloc[0]-fl[(fl.C==1e24)&(fl.L_ctx==2048)].L.iloc[0]:.3f}。')
W('- 由于质量成本不受注意力影响，L_ctx 越长，质量越早启动：从 2048 到 131072，C₁ 下降为原来的约 1/7(表4、图5 左)，但转移的类型与阶段顺序不变。可见 L_ctx 只平移结构性转移发生的位置，不改变其本质。'); W('')
W('## 6  敏感性与不确定性'); W('')
W('**参数不确定性**：从问题二的 c_N、c_D 自助分布中抽取 150 组，同时让 η_p 在 [0.46, 0.68] 内均匀取值、Q_ref 做 ±3% 扰动。')
T(UQ.rename(columns={'Unnamed: 2': 'quantile'})[['C', 'g_form', 'quantile', 'N', 'D', 'Q', 'L', 'share_quality', 'tpp']])
T(RS)
W(f'状态判定在 10²² 和 10²⁴ 下 100% 稳定。在 10¹⁹ 处，指数型的状态在 R1 与 R2 之间各占约一半，幂函数型有 7.3% 的抽样仍是 R0，这再次说明 10¹⁹ 位于转移带内。'); W('')
W('**基线质量 Q₀**(取问题一各域的 Q)：')
T(Q0S[['Q0_scenario', 'Q0', 'C', 'g_form', 'Q', 'share_quality', 'tokens_per_param', 'L', 'regime']])
W('Q₀ 越高，质量的提升空间越小，启动越晚：Q₀ 取 arxiv 的 0.804 时，指数型和幂函数型在 10¹⁹ 下都不投质量(R0)。高预算下各情景都收敛到 Q*≈1，Loss 差异 < 10⁻³。'); W('')
W('**成本参数 ±50%(γ)与 ±20%(λ)对质量启动临界预算 C₁(一阶判据)的影响**：')
T(CP, '.3e')
W('C₁ 对 γ 近似呈幂律敏感：γ 加倍，指数型的 C₁ 约升高 4.6 倍。但所有情景下 C₁ 都在 10¹⁷–10²⁰ 之间，结构性转移的存在性与顺序不受影响。')
F('F08_uncertainty_Q0.png', '图8  不确定性与 Q₀ 情景')
F('F10_gains.png', '图10  质量投入与配比优化的收益')
W('## 7  结论与给问题四的接口'); W('')
W('- **最优策略**：p 取问题一的 p*(与预算无关)，(N, D, Q) 由上述模型求解，三档预算的数值结果见第 3 节。')
W('- **结构性转移**：有明确的数学定义(类型 Ⅰ/Ⅱ/Ⅲ)和识别方法(状态序列+二分法、分段幂律+BIC、边际收益排序)。结论是：低预算"只扩规模"→临界预算后"以质换量"→质量饱和后"回归规模扩张"→数据墙后"只加参数"。临界预算有解析判据：连续型 g′(Q₀) = g′*(C)，跳跃型 L*(Q₀) = L*(1)。')
W('- **成本函数**：决定转移位置(相差约 50 倍)与形态(连续/跳跃)。本文的改进型体现了"完美数据不可得"，在高预算下仍保留约 6% 的质量开销。')
W('- **L_ctx**：只按 k(L) 平移转移位置；L ≥ L_crit=30000 时注意力成为主导开销。')
W('- **对问题四的启示**：在当前主流预算(≥10²³)下，质量已接近饱和，前沿能力的进一步增长主要来自规模与非规模技术进步；而质量与配比带来的收益主要体现在中小预算区间(见图10)。'); W('')
W('## 8  局限'); W('')
W('- 广义律继承了问题二的假设：经典部分来自 Chinchilla 型校准数据，质量乘子来自半合成的 B6/B7，η_p 只由三个尺度确定。')
W('- 成本模型把质量处理与训练视为同一种 FLOP，没有考虑实际中数据处理可以使用更便宜的算力(如小模型打分)。若质量处理更便宜，C₁ 会进一步提前(见 γ 敏感性)。')
W('- 数据墙只用 C7 中的最大训练 token 数(18T)作为单一锚点，没有区分各领域的数据供给上限；若考虑分领域的上限，p 在超大预算下可能被迫偏离 p*。')
W('- 改进型成本函数的标定(与指数型在 Q=0.9 处相等)属于建模选择，本文只用它比较结构形态，不作为唯一依据。'); W('')
W('## 附录  过程文件与复现'); W('')
idx = pd.read_csv('out/PROCESS_FILE_INDEX.csv') if os.path.exists('out/PROCESS_FILE_INDEX.csv') else None
if idx is not None:
    T(idx[['path', 'rows', 'description']])
W('复现：`bash code/run_all.sh`(依赖 numpy、pandas、scipy、matplotlib、tabulate；`data/` 下需包含 `q1_out/`、`q2_out/` 与 C7 文件)。'); W('')
W('> **AI 使用披露提示**：赛题第五部分规定，AI 不得代替完成核心建模、推导与论证，论文末尾须披露所用 AI 工具、使用环节与贡献范围。请参赛队伍自行核验并理解本报告中的模型与推导，按赛题要求如实披露。')
open('问题三求解报告.md', 'w').write('\n'.join(out)); print(len(out))
